<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class SecurityHeaders
{
    /**
     * Handle an incoming request.
     *
     * @param  \Closure(\Illuminate\Http\Request): (\Symfony\Component\HttpFoundation\Response)  $next
     */
    public function handle(Request $request, Closure $next): Response
    {
        $response = $next($request);

        // Only add headers to HTTP responses
        if (
            !$response instanceof \Illuminate\Http\Response &&
            !$response instanceof \Illuminate\Http\JsonResponse &&
            !$response instanceof \Inertia\Response
        ) {
            return $response;
        }

        // Content Security Policy
        // Remove any existing CSP header first to prevent conflicts (e.g., from server config, CDN, or other sources)
        $response->headers->remove('Content-Security-Policy');
        $response->headers->remove('Content-Security-Policy-Report-Only');
        
        $csp = $this->buildContentSecurityPolicy($request);
        $response->headers->set('Content-Security-Policy', $csp, true); // true = replace any existing

        // HTTP Strict Transport Security (HSTS)
        if ($request->isSecure()) {
            $response->headers->set(
                'Strict-Transport-Security',
                'max-age=31536000; includeSubDomains; preload'
            );
        }

        // X-Frame-Options - Prevent clickjacking
        // Allow framing for preview mode in page builder
        if ($request->query('preview') === 'true') {
            $response->headers->set('X-Frame-Options', 'SAMEORIGIN');
        } else {
            $response->headers->set('X-Frame-Options', 'DENY');
        }

        // X-Content-Type-Options - Prevent MIME sniffing
        $response->headers->set('X-Content-Type-Options', 'nosniff');

        // X-XSS-Protection - Enable XSS filtering
        $response->headers->set('X-XSS-Protection', '1; mode=block');

        // Referrer Policy - Control referrer information
        $response->headers->set('Referrer-Policy', 'strict-origin-when-cross-origin');

        // Permissions Policy (formerly Feature Policy)
        $permissionsPolicy = $this->buildPermissionsPolicy();
        $response->headers->set('Permissions-Policy', $permissionsPolicy);

        // Cross-Origin Embedder Policy - Disabled for shared hosting compatibility
        /*
        if (!app()->environment('local')) {
            $response->headers->set('Cross-Origin-Embedder-Policy', 'require-corp');
            $response->headers->set('Cross-Origin-Opener-Policy', 'same-origin');
            $response->headers->set('Cross-Origin-Resource-Policy', 'same-origin');
        }
        */

        // Remove server information
        $response->headers->remove('Server');
        $response->headers->remove('X-Powered-By');

        // Cache control for sensitive pages
        if ($this->isSensitivePage($request)) {
            $response->headers->set('Cache-Control', 'no-cache, no-store, must-revalidate, private');
            $response->headers->set('Pragma', 'no-cache');
            $response->headers->set('Expires', '0');
        }

        return $response;
    }

    /**
     * Build Content Security Policy header
     */
    /**
     * Build Content Security Policy header
     */
    private function buildContentSecurityPolicy(Request $request): string
    {
        // Use the nonce generated by Vite
        $nonce = \Illuminate\Support\Facades\Vite::cspNonce();

        if (!$nonce) {
            $nonce = base64_encode(random_bytes(16));
        }

        // Store nonce for use in views
        app()->instance('csp-nonce', $nonce);

        // Determine frame-ancestors based on preview mode
        $frameAncestors = $request->query('preview') === 'true' ? "'self'" : "'none'";

        // Base URLs for external services
        $fontHosts = ["https://fonts.googleapis.com", "https://fonts.bunny.net", "https://fonts.gstatic.com"];
        $mapHosts = ["https://basemaps.cartocdn.com", "https://*.basemaps.cartocdn.com"];
        $videoHosts = ["https://www.youtube.com", "https://www.youtube-nocookie.com", "https://player.vimeo.com", "https://vimeo.com"];

        // Define directives as an associative array to avoid duplication
        $directives = [
            'default-src' => ["'self'"],
            'style-src' => array_merge(["'self'", "'unsafe-inline'"], $fontHosts),
            'font-src' => array_merge(["'self'"], $fontHosts),
            'img-src' => ["'self'", "data:", "https:"],
            'media-src' => ["'self'", "https:"],
            'connect-src' => array_merge(["'self'", "https:", "wss:"], $mapHosts),
            'worker-src' => ["'self'", "blob:"],
            'child-src' => ["'self'", "blob:"],
            'object-src' => ["'none'"],
            'base-uri' => ["'self'"],
            'form-action' => ["'self'"],
            'frame-src' => array_merge(["'self'"], $videoHosts),
            'frame-ancestors' => ["{$frameAncestors}"],
        ];

        // Conditional CSP updates for Local Development
        if (app()->environment('local', 'development')) {
            $viteHost = is_file(public_path('hot')) ? rtrim(file_get_contents(public_path('hot'))) : 'http://127.0.0.1:5173';
            $localHosts = ["{$viteHost}", "http://localhost:5173", "http://127.0.0.1:5173"];
            $wsHosts = array_map(fn($h) => str_replace('http://', 'ws://', $h), $localHosts);

            // Merge local hosts into relevant directives
            $directives['style-src'] = array_merge($directives['style-src'], $localHosts);
            $directives['font-src'] = array_merge($directives['font-src'], $localHosts);
            $directives['img-src'] = array_merge($directives['img-src'], $localHosts);
            $directives['media-src'] = array_merge($directives['media-src'], $localHosts);
            $directives['connect-src'] = array_merge($directives['connect-src'], $localHosts, $wsHosts, ["ws:", "wss:"]);
            
            // Script rules for development
            $directives['script-src'] = ["'self'", "'unsafe-inline'", "'unsafe-eval'", "blob:"];
            $directives['script-src'] = array_merge($directives['script-src'], $localHosts);
            
            $directives['script-src-elem'] = ["'self'", "'unsafe-inline'", "blob:"];
            $directives['script-src-elem'] = array_merge($directives['script-src-elem'], $localHosts);
        } else {
            // Production Script Rules
            $directives['script-src'] = ["'self'", "'unsafe-inline'", "'unsafe-eval'", "blob:", "'nonce-{$nonce}'"];
            $directives['script-src-elem'] = ["'self'", "'unsafe-inline'", "blob:", "'nonce-{$nonce}'"];
            
            // Enforce HTTPS in production
            $directives['upgrade-insecure-requests'] = [];
        }

        // Format directives for the header
        $policyStrings = [];
        foreach ($directives as $name => $values) {
            if (empty($values)) {
                $policyStrings[] = $name;
            } else {
                $policyStrings[] = $name . ' ' . implode(' ', array_unique($values));
            }
        }

        return implode('; ', $policyStrings);
    }

    /**
     * Build Permissions Policy header
     */
    private function buildPermissionsPolicy(): string
    {
        $policies = [
            'accelerometer=()',
            'autoplay=()',
            'camera=()',
            'cross-origin-isolated=()',
            'display-capture=()',
            'encrypted-media=()',
            'fullscreen=(self)',
            'geolocation=()',
            'gyroscope=()',
            'keyboard-map=()',
            'magnetometer=()',
            'microphone=()',
            'midi=()',
            'payment=()',
            'picture-in-picture=()',
            'publickey-credentials-get=()',
            'screen-wake-lock=()',
            'sync-xhr=()',
            'usb=()',
            'web-share=()',
            'xr-spatial-tracking=()',
        ];

        return implode(', ', $policies);
    }

    /**
     * Check if the current page is sensitive (admin, auth, etc.)
     */
    private function isSensitivePage(Request $request): bool
    {
        $sensitiveRoutes = [
            'admin/*',
            'login',
            'register',
            'password/*',
            'settings/*',
            'dashboard',
        ];

        foreach ($sensitiveRoutes as $route) {
            if ($request->is($route)) {
                return true;
            }
        }

        return false;
    }
}